layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    - archit2604
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: archit-rungta-883156193
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: rungtarchit1
  # unsplash: your_username
  # vk: your_username
  website: https://archit2604.github.io/
  # youtube: your_username

topics:
  - name: Control Theory
    image_url: images/CT.jpg

  - name: ROS
    web_url: https://www.ros.org/
    image_url: images/ROS.png

  - name: Autonomous Navigation
    image_url: images/An.jpg
  
  - name: Computer Vision
    image_url: images/CV.jpeg

  - name: Reinforcement Learning
    image_url: images/RL.jpg